"""Regenerate src/15_hymn_library.gen.js from tools/jukebox_extra.js, then rebuild.

The arrays come from tools/jukebox_extra.js (single source, also used by the
jukebox build). Run tools/build_game.py afterwards (done automatically here).
"""
import io, os, subprocess, sys

BEGIN = '// ==== BEGIN HYMN LIBRARY (generated by tools/build_game_music.py — edit tools/jukebox_extra.js instead) ===='
END = '// ==== END HYMN LIBRARY ===='

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
extra = io.open(os.path.join(root, 'tools', 'jukebox_extra.js'), encoding='utf-8').read().rstrip()

io.open(os.path.join(root, 'src', '15_hymn_library.gen.js'), 'w', encoding='utf-8', newline='').write(
    BEGIN + '\n' + extra + '\n' + END + '\n')
print('src/15_hymn_library.gen.js refreshed:', len(extra), 'bytes of arrays')
subprocess.check_call([sys.executable, os.path.join(root, 'tools', 'build_game.py')])
